---
title: "613 hw9"
date: "2021/4/10"
output: word_document
---

#1
```{r}
library(tidycensus)
library(tidyverse)
library(dplyr)
library(ggplot2)
census_api_key("42f1de8c7e6161facaf5889926b6659f0418b101")
install=TRUE
y2015 <- load_variables(2015, "acs5", cache = TRUE)
View(y2015)
```

#2a
```{r}
data <- get_acs(geography = "county", 
              variables = c(medincome = "B01001A_011"), 
              state = 06, 
              year = 2015)
## Getting data from the 2011-2015 5-year ACS
data
```


#2b
```{r}
data2<-data %>%
  filter(estimate>3000)%>%
  arrange(desc(estimate))
data2
```


#2c
```{r}
data2%>%
  filter(estimate==51644, moe==667)
```


#2d
```{r}
ggplot(data = data2) +
  geom_boxplot(mapping = aes(x=estimate), fill="red")

```


#2e
```{r}
data2 %>%
  mutate(NAME = gsub(" County, California", "", NAME)) %>%
  ggplot(aes(x = estimate, y = reorder(NAME, estimate))) +
  geom_errorbarh(aes(xmin = estimate - moe, xmax = estimate + moe)) +
  geom_point(color = "blue", size = 3) +
  labs(title = "Household income by county in Vermont",
       subtitle = "2014-2018 American Community Survey",
       y = "",
       x = "ACS estimate (bars represent margin of error)")

```